base: !include ../base.yaml

batch_size: 1

# Model
model: "PointFeatureToGridGroupUNetAhmedBody"
hidden_channels:
  - 86
  - 86
  - 86
  - 86
num_levels: 3
use_rel_pos_embed: true

# Loggers
logger_types: ["wandb", "tensorboard"] # ["tensorboard", "wandb"]
project_name: "ahmed_body"
entity: "nvr-ai-algo"
run_name: "TriplaneUNet"

# dataset
data_module: "AhmedBodyDataModule.v2"
every_n_data: 10 # downsample 1/10
loss_name: "TruncatedMSELoss"
eval_loss_name: "MSELoss"
