# Standard Python logging configuration, as described here:
# https://docs.python.org/3.10/library/logging.config.html
version: 1
disable_existing_loggers: false

output: ???
rank: ???

formatters:
  default:
    format: "[%(asctime)s - %(name)s - %(levelname)s] %(message)s"
    datefmt: "%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: ${...loggers.tpunet.level}
    formatter: default

  file:
    class: logging.FileHandler
    filename: ${...output}/train_${...rank}.log
    level: ${...loggers.tpunet.level}
    formatter: default

loggers:
  tpunet:
    handlers: [console, file]
    level: INFO
    propagate: false
